### ISSUE TITLE
Insert inclination

### ISSUE THREAD

**Issue by mkelley** [lsst-sssc/lsst-simulation#12]
I'm checking the database as on the science platform, and the inclinations are all zero:
```
incl_check = pd.read_sql('''
SELECT
    min(incl),max(incl)
FROM mpcorb
''', con)
print('inclination check')
print(incl_check)
```
```
inclination check
   min  max
0  0.0  0.0
```
Can this be fixed?

**Comment by mjuric** [comment]
Why indeed they are... embarrassing. Thanks for reporting!

Looks like a data import snafu, I'll investigate & try to fix it this evening.

The other orbital elements columns seem OK (`n` isn't filled out because it's redundant with `a`, and other metadata columns aren't very relevant for the simulation).

**Comment by mjuric** [comment]
Hi @mkelley -- this should be fixed now (reopen if the issue persists).
